### ISSUE TITLE
 First Week on GitHub Training Lab Link on Introduction to GitHub module Leading to a 404 error

### ISSUE THREAD

**Issue by Peter-Nyarunda** [microsoft/Web-Dev-For-Beginners#1018]
**Describe the bug**
Hyperlink leading to First Week on Github Training Lab opens to a 404 error page.

**To Reproduce**
1. Go to https://github.com/microsoft/Web-Dev-For-Beginners/tree/main/1-getting-started-lessons/2-github-basics under Review & Self-study
2. Click on the "First Week on GitHub" hyperlink

**Expected behavior**
The link should open to a GitHub lab which should provide a practice on Github Basics.

**Screenshots**
<img width="615" alt="image" src="https://user-images.githubusercontent.com/118875460/208931772-03465211-28dd-4d78-9f0b-6d9f24a9e6b9.png">

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser: Chrome
 - Version : 108.0.5359.125

**Comment by Peter-Nyarunda** [comment]
This issue has been opened also at https://github.com/microsoft/Web-Dev-For-Beginners/issues/1023

**Comment by saragibby** [comment]
Resolved in #1042
