### ISSUE TITLE
[TRANSLATIONS]

### ISSUE THREAD

**Issue by Kiddc66** [microsoft/Web-Dev-For-Beginners#1022]
- [x] Base README.md
- [x] for-teachers.md
- [x] Quizzes
- [x] 1-getting-started-lessons base README
   - [x] intro-to-programming-languages README
   - [x] intro-to-programming-languages assignment
   - [x] github-basics README
   - [x] accessibility README
   - [x] accessibility assignment
- [x] 2-js-basics base README
   - [x] data-types README
   - [x] data-types assignment
   - [x] functions-methods README
   - [ ] functions-methods assignment
   - [x] making-decisions README
   - [x] making-decisions assignment
   - [x] arrays-loops README
   - [x] arrays-loops assignment
- [ ] 3-terrarium base README
   - [x] intro-to-html README
   - [x] intro-to-html assignment
   - [x] intro-to-css README
   - [x] intro-to-css assignment
   - [x] intro-to-DOM-and-closures README
   - [x] intro-to-DOM-and-closures assignment
- [ ] 4-typing-game base README
   - [ ] typing-game README
   - [ ] typing-game assignment
- [ ] 5-browser-extension base README
   - [ ] about-browsers README
   - [ ] about-browsers assignment
   - [ ] forms-browsers-local-storage README
   - [ ] forms-browsers-local-storage assignment
   - [ ] background-tasks-and-performance README
   - [ ] background-tasks-and-performance assignment
   - [ ] solution base README
   - [ ] start base README
- [ ] 6-space-game base README
   - [ ] introduction README
   - [ ] introduction assignment
   - [ ] drawing-to-canvas README
   - [ ] drawing-to-canvas  assignment
   - [ ] moving-elements-around README
   - [ ] moving-elements-around  assignment
   - [ ] collision-detection README
   - [ ] collision-detection assignment
   - [ ] keeping-score README
   - [ ] keeping-score assignment
   - [ ] end-condition README
   - [ ] end-condition assignment
- [ ] 7-bank-project base README
   - [ ] template-route README
   - [ ] template-route assignment
   - [ ] forms README
   - [ ] forms  assignment
   - [ ] data README
   - [ ] data assignment
   - [ ] state-management README
   - [ ] state-management  assignment
   - [ ] solution base README
   - [ ] API base README

**Comment by saragibby** [comment]
@Kiddc66 is there an issue you spotted with the translations or any missing? Thanks!

**Comment by saragibby** [comment]
Closing this issue with no description as to what is the item to be addressed.
