### ISSUE TITLE
Broken URL in Intro to GitHub Assignment

### ISSUE THREAD

**Issue by kyletower** [microsoft/Web-Dev-For-Beginners#1023]
**Describe the bug**
There is a broken URL in the Intro to GitHub assignment

**To Reproduce**
1. Go to https://github.com/microsoft/Web-Dev-For-Beginners/tree/main/1-getting-started-lessons/2-github-basics
2. Click on Assignment: Complete [the First Week on GitHub training lab](https://lab.github.com/githubtraining/first-week-on-github)
3. See error

**Expected behavior**
This link should land on a page with the assignment.

**Comment by 31Sanskrati** [comment]
Along with the above error, in **Review & Self Study** section [lab.github.com](https://lab.github.com/) link is not working.

**Comment by 31Sanskrati** [comment]
I don't think the error occurs due to a broken link as the official website of github lab is showing the exact same error.

**Comment by bellodavid** [comment]
Is this issue still open?

**Comment by saragibby** [comment]
Duplicate of #1018

**Comment by saragibby** [comment]
Resolved in #1042
