### ISSUE TITLE
Hope this helps 

### ISSUE THREAD

**Issue by Katerbug1984** [microsoft/Web-Dev-For-Beginners#1029]
#**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saragibby** [comment]
@Katerbug1984 is there a particular bug that you are reporting? Add detail to the prompts provided and we can address the bug you found. Thanks!

**Comment by saragibby** [comment]
Closing this issue as it has no description or information on what issue to address. @Katerbug1984 please open a new issue with a complete description for any item you find.
