### ISSUE TITLE
Explain your feature request 

### ISSUE THREAD

**Issue by Katerbug1984** [microsoft/Web-Dev-For-Beginners#1030]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by saragibby** [comment]
@Katerbug1984 is there a particular feature request you are requesting? Add detail to the prompts provided and we can address your request. Thanks!

**Comment by saragibby** [comment]
Closing this issue as it has no description or information on what issue to address. @Katerbug1984 please open a new issue with a complete description for any item you find.
