### ISSUE TITLE
Dead Links

### ISSUE THREAD

**Issue by cboydstun** [microsoft/Web-Dev-For-Beginners#1041]
**Describe the bug**
Near the bottom of [GitHub Basics](https://github.com/microsoft/Web-Dev-For-Beginners/tree/main/1-getting-started-lessons/2-github-basics) are three dead links that all return 404 errors:
- [labs.github.com](https://lab.github.com/)
- [First Week on Github](https://lab.github.com/githubtraining/first-week-on-github)
- [the First Week on GitHub training lab](https://lab.github.com/githubtraining/first-week-on-github)

**To Reproduce**
1. Go to [GitHub Basics](https://github.com/microsoft/Web-Dev-For-Beginners/tree/main/1-getting-started-lessons/2-github-basics)
2. Scroll down to the "[Review & Self Study" section](https://github.com/microsoft/Web-Dev-For-Beginners/tree/main/1-getting-started-lessons/2-github-basics#review--self-study)
3. See the three dead links described above.

**Expected behavior**
Working links. 😛

**Comment by Javali-M** [comment]
Please assign this issue to me, I'll replace them. The links are dead because Learning Lab is now deprecated in favour of GitHub Skills (https://github.blog/2022-06-06-introducing-github-skills/)

**Comment by saragibby** [comment]
Resolved with #1042
