### ISSUE TITLE
https://play.google.com/store/apps/dev?id=8802462833480602617

### ISSUE THREAD

**Issue by Teezbrowdy** [microsoft/Web-Dev-For-Beginners#1046]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by saragibby** [comment]
@Teezbrowdy closing this issue as it has no details. Please open a new one if you have any feature requests and an item that needs updating. Thanks!
