### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by GreggJEduardo** [microsoft/Web-Dev-For-Beginners#1049]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saragibby** [comment]
@GreggJEduardo closing this issue as it lacks detailed information and description. Please open a new issue if/when you spot an issue, or have a feature request, including a full descriiption. Thanks!
