### ISSUE TITLE
Browser Extension Manifest version 2 is deprecated

### ISSUE THREAD

**Issue by cboydstun** [microsoft/Web-Dev-For-Beginners#1060]
**Describe the bug**
[Lesson 12 "About Browsers"](https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/5-browser-extension/1-about-browsers/README.md)

Upon installation of our extension boilerplate and adding it to the browser, we're given an error. 
```bash
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
```

**To Reproduce**
1. Go to `Web-Dev-For-Beginners/5-browser-extension/starter/`
2. Run `npm run build`
3. Load unpacked extension into browser
4. See error on extensions card 

**Expected behavior**
Updated to Manifest version 3.

**Screenshots**
![image](https://user-images.githubusercontent.com/52934303/213572309-b6329d63-80d1-4fe2-bea6-6001a3649045.png)
![image](https://user-images.githubusercontent.com/52934303/213572383-06b31f92-2e8c-42c9-b02d-4fb8a63a42e9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 22

**Comment by saragibby** [comment]
Thanks for spotting and reporting this @cboydstun! This should now be resolved on main from [this commit](https://github.com/microsoft/Web-Dev-For-Beginners/commit/067dfd171f473b46c849de9f2844dd2b447c883d).
