### ISSUE TITLE
Lesson 17 Dead Link

### ISSUE THREAD

**Issue by cboydstun** [microsoft/Web-Dev-For-Beginners#1065]
**Describe the bug**
There is a dead link at the end of the section Lesson 17 [Pre-Lecture Quiz](https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/6-space-game/3-moving-elements-around/README.md#pre-lecture-quiz). The link reads "alternatives to this pattern" and goes to https://www.html5rocks.com/en/tutorials/canvas/performance/, but redirects to https://web.dev/learn/. 

**To Reproduce**
1. Go to Lesson 17 [Pre-Lecture Quiz](https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/6-space-game/3-moving-elements-around/README.md#pre-lecture-quiz)
2. Scroll to the bottom of the section
3. Find the link "Read about [alternatives to this pattern](https://www.html5rocks.com/en/tutorials/canvas/performance/)."
4. Click and experience the redirect to [a different page](https://web.dev/learn/) devoid of relevant information.

**Comment by KetanParmar03** [comment]
can you assign me this issue?

I am interest in solve this issue?

**Comment by KetanParmar03** [comment]
can you suggest what should i do next?

**Comment by KetanParmar03** [comment]
so, please can you assign to me this issue?

**Comment by cboydstun** [comment]
@KetanParmar03 I can't assign anything in this repo. I'm pretty sure the dead link should to this article on [canvas performance](https://web.dev/canvas-performance/) just based on the URL.

**Comment by KetanParmar03** [comment]
ok, sir thank you
