### ISSUE TITLE
Need update installed performance ASAP

### ISSUE THREAD

**Issue by Leeroy28** [microsoft/Web-Dev-For-Beginners#1083]

**Comment by Addysource** [comment]
He-eye! I have the same problem as yours, Wi-Fi connection has always been a nightmare for me, I know that you guys can make all sorts of things possible perfectly any advice or suggestions on how can I fix it or someone can help me out please? Thank you!

**Comment by saragibby** [comment]
@Addysource this repository focuses on Web Development, to take beginners through lessons on HTML, CSS and JavaScript. Any issues with Wi-Fi conenction and setup are not addressed in this repo. If you find any issues within this repository, please feel free to open a new issue with details of what you found so we can address it. Thank you!
