### ISSUE TITLE
Broken link report

### ISSUE THREAD

**Issue by nicobucodiguito** [microsoft/Web-Dev-For-Beginners#1101]
Hey!
In the section of - https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/6-space-game/3-moving-elements-around/README.md
"✅ Can you think of a reason why redrawing your hero many frames per second might accrue performance costs? Read about alternatives to this pattern"
The URL doesn't redirect to any canvas performance article, it only redirects to https://web.dev
Maybe https://web.dev/fast is the article originally meant, but the site seems to have changed the domain and the article is not explicitly about canvas, more about other broader concepts

**Comment by saragibby** [comment]
Thanks for pointing this out @nicobucodiguito! After looking back at this, it seems this would best be updated to: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Optimizing_canvas

**Comment by Swarga-codes** [comment]
@saragibby can you assign me this issue?

**Comment by Swarga-codes** [comment]
@saragibby Can you please check my PR #1106 on this issue? , I made the necessary changes on this.

**Comment by saragibby** [comment]
Fixed in #1105
