### ISSUE TITLE
Variable not declared / ambiguous usage

### ISSUE THREAD

**Issue by suryakapila** [microsoft/Web-Dev-For-Beginners#1103]
**Describe the bug**
Usage of undeclared const variables
 
**To Reproduce**
1. Go to '../src/index.js'
2. Click on 'fucntion init()'
3. const storedRegion = localStorage.getItem('regionName');
4. variable 'regionName' not declared.

**Expected behavior**
It should be replaced with 'region' as declared in the //form fields section of index.js

**Comment by BamaCharanChhandogi** [comment]
Hey @suryakapila, I have removed all 'regionName' Keywords in index.js. Check the PR #1120

**Comment by saragibby** [comment]
Thank you for reporting this issue! Closing this issue has fixed has been merged on to the main branch.
