### ISSUE TITLE
Aviator predictor app login details unlimited

### ISSUE THREAD

**Issue by Rabbisikder1821** [microsoft/Web-Dev-For-Beginners#1119]
### Discussed in https://github.com/microsoft/Web-Dev-For-Beginners/discussions/1109

<div type='discussions-op-text'>

<sup>Originally posted by **Tysoftwares** March 27, 2023</sup>
Guys let make use of this app and generate steady income daily   chat me up on tysoftwares@gmail.com for details </div>

**Comment by Tongtei** [comment]
Ohh interesting

**Comment by Gabby1024** [comment]
Ooooh, well said!

**Comment by yerry44** [comment]
help me too, I have the application, but I don't have the login data.

**Comment by favorine** [comment]
Cool

**Comment by saragibby** [comment]
@Rabbisikder1821 thank you for your interest in this repo! With nothing actionable here for this curriculum, I am going to close this issue. In the future, as you have questions, hit any issues, or have feature ideas, please open a new issue. Thanks!
