### ISSUE TITLE
@sbatten Any news ? Can you reproduce this behavior in a GNU/Linux distro ?

### ISSUE THREAD

**Issue by Just6789** [microsoft/Web-Dev-For-Beginners#1124]
@sbatten Any news ? Can you reproduce this behavior in a GNU/Linux distro ?

_Originally posted by @G-Ray in https://github.com/microsoft/vscode/issues/58383#issuecomment-423955747_
![Screenshot_20230426-122051](https://user-images.githubusercontent.com/129498517/234749729-edc29022-c25a-44f3-8563-2e458af71625.png)
![Screenshot_20230426-084125](https://user-images.githubusercontent.com/129498517/234749733-9e2bcba1-b640-470d-9516-9f7529bb805e.png)
![Screenshot_20230426-083936](https://user-images.githubusercontent.com/129498517/234749735-d6012748-8218-46d1-83fd-a6823fbe2826.png)

**Comment by Just6789** [comment]
> reproduce
Dawn issues

**Comment by saragibby** [comment]
@Just6789 thank you for your interest in this repo! With nothing noted or described that is actionable to this repository, I am going to close this issue. In the future, as you have questions, hit any issues, or have feature ideas, please open a new issue. Thanks!
