### ISSUE TITLE
Pre Lecture Quiz won't open in offline mode

### ISSUE THREAD

**Issue by saivishnu725** [microsoft/Web-Dev-For-Beginners#113]
While doing the course offline using [docsify](docsify.js.org), in the first topic i.e.., 1-getting-started-lessons/1-intro-to-programming-languages/ there comes a pre-lecture-quiz.md the docsify transfers the link to the root .github folder where the file is not present hence giving a 404 status.

1. Start the offline way as described in the [README](https://github.com/microsoft/Web-Dev-For-Beginners#offline-access)
2. Scroll to 'http://localhost:3000/#/1-getting-started-lessons/1-intro-to-programming-languages/README'
3. Scroll down to 'pre-lecture-quiz' and click on it.
4. See the 404 error.
5. Error being that it goes to [this](http://localhost:3000/#/.github/pre-lecture-quiz) while it should be going to [this](http://localhost:3000/#/1-getting-started-lessons/1-intro-to-programming-languages/.github/pre-lecture-quiz) .
6. The problem is with the way Github(links starting from '.' are of the same folder) and Docsify(links starting from '.' are from the root folder) handles dynamic links .

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Brave Browser(based on Chromium)

**Comment by jlooper** [comment]
Can you try again with a new Docsify build, as we have added a relative path parameter to the installation? Thanks

**Comment by saivishnu725** [comment]
It works now. Thank you for the fix.
