### ISSUE TITLE
Lesson 1 | Pre-Lecture Quiz not working.

### ISSUE THREAD

**Issue by Codewith-Akshut** [microsoft/Web-Dev-For-Beginners#114]
**Describe the bug**
A clear and concise description of what the bug is that the lesson 1 Pre-Lecture Quiz isn't working. When any option clicked then it isn't showing selection.

**To Reproduce**
1. Go to https://github.com/microsoft/Web-Dev-For-Beginners.
2. Scroll down to Lessons.
3. Click on Lesson 1 link.
4. Scroll down to Pre-Lecture Quiz.
5. Click on Pre-Lecture Quiz link.
6. Try clicking on any of the options available for the quiz questions.
7. See error

**Expected behavior**
When any option selected then the selection would have appeared but isn't appearing.

**Screenshots**
![image](https://user-images.githubusercontent.com/76103163/103149697-d25be580-4791-11eb-8243-06ca0168753e.png)
When the option clicked then no selection appearing.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 87.0.4280.88

**Comment by anjaliasha123** [comment]
Even I am facing the same issue.

**Comment by imrealrakibul** [comment]
> Even I am facing the same issue.

Same here.

**Comment by jlooper** [comment]
Hello, currently these quizzes are not live which is a problem we are trying to fix by my migrating them to Microsoft forms. Please stay tuned and thank you
