### ISSUE TITLE
Dev Home GitHub Extension (Preview)

### ISSUE THREAD

**Issue by StShadow6** [microsoft/Web-Dev-For-Beginners#1140]
Dev Home GitHub Extension (Preview) https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701?hl=en-us&gl=us&icid=CNavAppsWindowsApps

**Comment by saragibby** [comment]
@StShadow6 thank you for your interest in this repo and sharing the link the Windows terminal app! With nothing actionable here for this curriculum, I am going to close this issue. In the future, as you have questions, hit any issues, or have feature ideas, please open a new issue. Thanks!
