### ISSUE TITLE
Language fix code/transfer 

### ISSUE THREAD

**Issue by James6811** [microsoft/Web-Dev-For-Beginners#1157]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by saragibby** [comment]
@James6811 thank you for your interest in this repo! With nothing actionable here, I am going to close this issue. In the future, as you have questions, hit any issues, or have feature ideas, please open a new issue. Thanks!
