### ISSUE TITLE
Okay, I understand. I installed `gnome-keyring` and it works, so this is a duplicate of #205.

### ISSUE THREAD

**Issue by lanjos78** [microsoft/Web-Dev-For-Beginners#1158]
Okay, I understand. I installed `gnome-keyring` and it works, so this is a duplicate of #205.

_Originally posted by @Klikini in https://github.com/microsoft/vscode-docker/issues/1515#issuecomment-571434664_
            ---------------------------------------------------------------------------------------

I was having this problem with the (Epiphany)browser Web 3.38.2 to synchronize firefox, the tip solved, Thanks!

**Comment by saragibby** [comment]
@lanjos78 thank you for your interest in this repo! From your note, it looks like you hit an issue with VS Code and Docker. If so, the repo you linked to above is the right spot for that question. With nothing actionable for this repository, I am going to close this issue. In the future, as you have questions, hit any issues, or have feature ideas, please open a new issue. Thanks!
