### ISSUE TITLE
How to start coding?

### ISSUE THREAD

**Issue by Rahullgowda** [microsoft/Web-Dev-For-Beginners#1278]
Can anyone please tell me a road map of coding and how to improve myself in the tech field,like now i started learning languages like c ,c++ and python,and what should I do next and what were the best ways and options to have the best life 🧬 please

**Comment by oluseguncodess** [comment]
Hey 👋🏾, i think it depends on what you want to do! There are different road maps for different roles!

**Comment by Rahullgowda** [comment]
Thats what I'm confused about , what are the options i have?

**Comment by oluseguncodess** [comment]
Oh okay, check out this website to view different roles and their roadmaps. Click [here](https://roadmap.sh/) 👈🏾

**Comment by TechCodeee** [comment]
> Can anyone please tell me a road map of coding and how to improve myself in the tech field,like now i started learning languages like c ,c++ and python,and what should I do next and what were the best ways and options to have the best life 🧬 please

hey mate, go with one particular language at a time as you seem to be begineer go with python learn its fundamentals and dive into dsa for better understanding. To get the clear understanding roadmap do visit @roadmap.sh which might help you to classify your learnings

**Comment by Ace-Aryal** [comment]
Mate, learn C and  C++ with medium level DSA if you have a good time , then you can choose webdev ,mobiledev , gamedev, AI/ML you can find the perfect roadmap on roadmash website

**Comment by Rishi-Singhal21** [comment]
Hey,
If you want to start coding and you are a complete beginner then start with C or C++. There are few reasons for that :- 

1. C/ C++ helps to build your logic as Python have multiple inbuilt functions which makes coding somehow easy. But if you code in C or C++ you have to code the logic for every action you performed.
2. You can start DSA with C++ as build your problem solving skills. In Python we already have functions for that.

And as for roadmap, start with fundamental concepts like : 
Data types, Strings, Looping statements, Conditional statements, basics of functions and Recursion
Then move towards Data Structures like Array, Stack, Linked list, Queue, searching and sorting 
After the basics you can start actual DSA concepts like: 
Dynamic Programming, Backtracking, Tree, Graph and some algorithms.

Practice and Consistency is must.

**Comment by divyakumari12** [comment]
Start with learning a programing language, say C++, basically basic concepts like data types, variables, loops, conditions, etc.
Do questions as much as you can so that you have a better understanding (e.g. Hackerrank, Hackerearth).
Practice regularly. as you should be consistent.
After this you can start Data Structures and Algorithms.

Build projects to apply your knowledge.

**Comment by Ernest3688** [comment]
first of all, decide on what area of programming you like and find a way to begin. you can decide to take tutorial classes and learn.

**Comment by softchris** [comment]
interesting thread but please keep this to discussions. Closing for now
