### ISSUE TITLE
Seeing the last question and options at the end of the quiz

### ISSUE THREAD

**Issue by meghatiku** [microsoft/Web-Dev-For-Beginners#133]
**Describe the bug**

_On completing the quiz and seeing the `Well done, you've completed the quiz` The screen shows the options from the answer options from the last question._

**To Reproduce**

_1. Go to 'https://nice-beach-0fe9e9d0f.azurestaticapps.net/quiz/1'
2. Click on 'Answer all questions'
3. Complete last question
4. See error with result_

**Expected behavior**

Only the completion message should be visible. The options from the last question should not be displayed.

**Screenshots**

<img width="1773" alt="Screenshot 2020-12-29 at 12 43 19 PM" src="https://user-images.githubusercontent.com/43341228/103265627-045c8a00-49d4-11eb-82aa-6c9b855095e6.png">
<img width="1782" alt="Screenshot 2020-12-29 at 12 43 02 PM" src="https://user-images.githubusercontent.com/43341228/103265637-09b9d480-49d4-11eb-9905-b0600ef88ccb.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome+ safari
 - Version : 10.15.4 

**Additional context**

I am not sure if this is expected by design. 😕

**Comment by jlooper** [comment]
It’s not very cool, is it? I will fix it, unless you can do a PR 🙏

**Comment by jlooper** [comment]
this should be all set
