### ISSUE TITLE
Small change in README file. 

### ISSUE THREAD

**Issue by saivishnu725** [microsoft/Web-Dev-For-Beginners#134]
1-getting-started-lessons/2-github-basics/README.md line 152 replace github.com/github/gitignore to https://github.com/github/gitignore
1. The offline viewer docsify thinks that it is a local file without the https:// .
2. I tried it in my forked repository and this change fixed it.

**Comment by jlooper** [comment]
Can you PR this for me please?

**Comment by jlooper** [comment]
Ah got it, thanks!
