### ISSUE TITLE
Not quite


### ISSUE THREAD

**Issue by zanins** [microsoft/Web-Dev-For-Beginners#137]
Not quite.

I'm looking for information on how to set Wifi SSID, Wifi Password, API Password, MQTT settings, etc, via API when the ESPHome device is in captive_portal mode. I don't believe setting all of these via any kind of API call is possible, though, I think at least Wifi SSID and Wifi Password are.

And the documentation for how to bring an ESPHome device developed on one Network to a different Network is lacking, if this is even possible without a recompile and reupload. I'd be happy to write the guide if I knew how to do these tasks. But I don't. That's why I'm looking for such documentation.

Thanks for the help.

_Publicado originalmente por @dlashua en https://github.com/esphome/feature-requests/issues/1053#issuecomment-751835951_

**Comment by jlooper** [comment]
Not relevant to this repo
