### ISSUE TITLE
Would be great to have hs support so I could use a binary sensor to control hue value and which is 0-360 (angles of a circle) and keeps repeating i.e. when it reaches 360 = 0 and loops again, in terms of endless loop it would not run code non-stop but rather the code allows the value to perform a second revolution by reseting to 0 at 360 degrees.

### ISSUE THREAD

**Issue by zanins** [microsoft/Web-Dev-For-Beginners#138]
Would be great to have hs support so I could use a binary sensor to control hue value and which is 0-360 (angles of a circle) and keeps repeating i.e. when it reaches 360 = 0 and loops again, in terms of endless loop it would not run code non-stop but rather the code allows the value to perform a second revolution by reseting to 0 at 360 degrees.

what else would be required to help add this feature?

https://github.com/FastLED/FastLED/wiki/FastLED-HSV-Colors

_Publicado originalmente por @ashp8i en https://github.com/esphome/feature-requests/issues/429#issuecomment-752205529_

**Comment by jlooper** [comment]
Sorry, this has nothing to do with this repo, perhaps it's opened by mistake
