### ISSUE TITLE
[Feature request][quiz-app] Query string to select language

### ISSUE THREAD

**Issue by hexatester** [microsoft/Web-Dev-For-Beginners#150]
**Is your feature request related to a problem? Please describe.**
I want the feature to select the language from the url, this is very helpful for people who don't understand English, especially those who read translations only.

**Describe the solution you'd like**
Something like `https://nice-beach-0fe9e9d0f.azurestaticapps.net/quiz/1?lang=id` will automatically change the language to id.

**Comment by jlooper** [comment]
yes! I was thinking along these same lines. Let's work on this

**Comment by jlooper** [comment]
ok, we can now specify the locale like this: /quiz/1?loc=id or /quiz/1?loc=en 👍

**Comment by hexatester** [comment]
Wow! that was fast. thank you

**Comment by jlooper** [comment]
I just edited your paths too :)
