### ISSUE TITLE
Correct grammar and punctuation mistakes

### ISSUE THREAD

**Issue by GintasS** [microsoft/Web-Dev-For-Beginners#153]
I've used this free [grammar checker](https://www.scribens.com/) and found some mistakes in the readme.md that I would recommend to fix. I also think there are a lot more in the individual sections, would be nice to have clean and mistake free course.

Possibly, there could be a lot of subtasks, one for the readme and others for the individual sections.

![image](https://user-images.githubusercontent.com/20372363/103445060-3beb6080-4c78-11eb-957c-9f2d293706df.png)

**Comment by jlooper** [comment]
That's cool but few of these are mistakes, so please do a manual check if you find typos. We have done our best, including using Ale, to present a 'clean and mistake-free course'. 

The mistakes I do see here are the possible omission of a period after 'template' and the omission of backticks for '/solutions'. Please PR actual typos if you do find them.

**Comment by jlooper** [comment]
closing this; please PR any typos you find and I will merge them if appropriate.

**Comment by GintasS** [comment]
Thanks 👍
