### ISSUE TITLE
Let's rethink the quizzes a little

### ISSUE THREAD

**Issue by jlooper** [microsoft/Web-Dev-For-Beginners#17]
Right now, the quizzes are intended to integrate with GitHub Classroom, but I haven't been able to make that work. If someone can create a GitHub Action to  grade quizzes, or suggest an alternate way to give ungraded feedback, please let's discuss here!

**Comment by theweird0ne** [comment]
How about using google forms to create the quiz.

**Comment by jlooper** [comment]
You gave me a good idea, we have quizzes with Microsoft forms! I will do some experiments.

**Comment by leemoneo** [comment]
> You gave me a good idea, we have quizzes with Microsoft forms! I will do some experiments.

Try Google sheets. With its add-ons too, it should do the trick. There is also surveymonkey.com

**Comment by jlooper** [comment]
We're at Microsoft so we'd use a home grown solution...investigating

**Comment by leemoneo** [comment]
True.
