### ISSUE TITLE
Audit all translations for completeness

### ISSUE THREAD

**Issue by jlooper** [microsoft/Web-Dev-For-Beginners#171]
Some translations are incomplete, so let's audit them and assign folks to fix.

If you'd like to start a draft PR while your translation work is in progress, please do so and follow these instructions: https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/TRANSLATIONS.md

- [ ] Spanish
- [ ] Indonesian
- [x] Hindi
- [ ] German
- [x] Japanese
- [x] Italian
- [x] Korean
- [ ] Portuguese
- [ ] Dutch
- [x] Chinese - Traditional
- [x] Chinese - Simplified
- [ ] Greek
- [x] Malay
- [ ] French
- [ ] Urdu
- [ ] Swahili
- [ ] Russian

**Comment by singh-ux** [comment]
Dutch

**Comment by marcoAtom** [comment]
I can help with chinese, but chinese is not in the list...

**Comment by unnati2201** [comment]
I can help with hindi

**Comment by jlooper** [comment]
@marcoAtom I'd love that, you can create a draft PR - would be super excited to have Chinese! @unnati2201 please feel free to look at what's needed to complete Hindi. Thanks everyone!

**Comment by jlooper** [comment]
@EugeneGohh thank you so much for the Malay translations! One thing, the Quiz app isn't yet localized; let me know if you would like to add Malay translations in the quiz-app json. Thanks!

**Comment by EugeneGohh** [comment]
@jlooper You're welcome, I would like to add Malay translations in the quiz-app json. May I know how can I localize it?

**Comment by jlooper** [comment]
> @jlooper You're welcome, I would like to add Malay translations in the quiz-app json. May I know how can I localize it?

hi, I've edited the translations instructions to show how to translate the quizzes. thanks so much! https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/TRANSLATIONS.md

**Comment by ilyaspiridonov** [comment]
Please consider using GItLocalize for managing translations @jlooper 
Here's an example of [a fork repo](https://github.com/donghoon-song/Web-Dev-For-Beginners) that is using Gitlocalize: [https://gitlocalize.com/repo/5627](https://gitlocalize.com/repo/5627)

**Comment by jlooper** [comment]
> Please consider using GItLocalize for managing translations @jlooper
> Here's an example of [a fork repo](https://github.com/donghoon-song/Web-Dev-For-Beginners) that is using Gitlocalize: https://gitlocalize.com/repo/5627

This is very interesting, and new to me! Let's look into it for this and future curricula!

**Comment by softchris** [comment]
> I can help with chinese, but chinese is not in the list...

go for it :)

**Comment by jlooper** [comment]
> > I can help with chinese, but chinese is not in the list...
> 
> go for it :) just create files on this format "filename".cn.md

Actually full instructions are in this file: https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/TRANSLATIONS.md

**Comment by matifali** [comment]
can you add Urdu in the list too?

**Comment by jlooper** [comment]
@matifali Please feel free to translate! thanks!

**Comment by deboralbarros** [comment]
I can help with portuguese

**Comment by jlooper** [comment]
@deboralbarros I would so love it!!

**Comment by Dav92ID28** [comment]
Russia

**Comment by morenyang** [comment]
It's cool! I can help with Chinese!

**Comment by Kartik125** [comment]
I want to work on this PR. I can help you with Hindi

**Comment by sukritijamwal** [comment]
I can help you with hindi

**Comment by harinibgithup** [comment]
I can't understand hindi sir

**Comment by jlooper** [comment]
> Russia

happy to have it in full!

**Comment by rajivransom** [comment]
I can do HINDI!

**Comment by josy66** [comment]
Eso si es Verda delo qué pasa en Denver co pura impocresia

**Comment by ssabawissabawi** [comment]
https://core.telegram.org/api

**Comment by Hiearl77** [comment]
최고 - korean

**Comment by tony955084** [comment]
https://shopee.tw/product/8698831/1217604708?smtt=0.293761175-1614965437.9

**Comment by tony955084** [comment]
https://shopee.tw/product/4778468/2316179947?smtt=0.293761175-1614967009.9

**Comment by mukeshmjn** [comment]
I can add punjabi can I go for it ?

**Comment by mukeshmjn** [comment]
Punjabi is not there i guess is Hindi also incomplete?

**Comment by mukeshmjn** [comment]
I can fix hindi

**Comment by mukeshmjn** [comment]
Can you assign hindi to me ? as its not complete some points are still left here are there i checked.

**Comment by jlooper** [comment]
hi, I'm not assigning as several folks are participating in these big tasks. Hindi is indeed incomplete, so please add a draft PR using our format if you choose

**Comment by spyze002** [comment]
put in English and  French , my country is Bilingual

**Comment by itskoma** [comment]
I can do it  hindi.

**Comment by FranciscoImanolSuarez** [comment]
I can help by translating into Spanish.

**Comment by jlooper** [comment]
> I can help by translating into Spanish.

I'd be very happy if you could @FranciscoImanolSuarez - the Spanish translations were done by machine and about 25% I think were corrected. thank you for any additional help!

**Comment by FranciscoImanolSuarez** [comment]
Perfect @jlooper, count on my help, I'll clone the repository and start reading the translations made and then I'll start translating.

**Comment by FranciscoImanolSuarez** [comment]
Hi @jlooper 🙋‍♂️👨‍🚀

I am going to do multiple PR these days, I am working on the translations already made to remove the neutrality of the words and correct errors or translations that do not go.

For example: "Assembly" is "Assembly", not "ensamblador".

Github in Spanish is Github, Java in Spanish is Java, since they are names.

Let me know if i'm wrong

**Comment by jlooper** [comment]
> Hi @jlooper 🙋‍♂️👨‍🚀
> 
> I am going to do multiple PR these days, I am working on the translations already made to remove the neutrality of the words and correct errors or translations that do not go.
> 
> For example: "Assembly" is "Assembly", not "ensamblador".
> 
> Github in Spanish is Github, Java in Spanish is Java, since they are names.
> 
> Let me know if i'm wrong

hi, thank you! the only correction I have is GitHub (capitalization issue) - otherwise I agree!

Can you create one PR per lesson grouping? It can remain in draft until you're ready for me to merge. Thank you!

**Comment by FranciscoImanolSuarez** [comment]
@jlooper  I just sent my PR 🚀

I keep working on other files. 👨‍🚀🤓

**Comment by Tridence** [comment]
I can work on Swahili☺️✨

**Comment by Chongruiyuan893** [comment]
#171

**Comment by Chongruiyuan893** [comment]
#228 #263 #261 #262 #260 #

**Comment by therajatrai** [comment]
I would love to work on Hindi Translations.
I am from India and have good command over the language.  Can I ?

**Comment by Dsompa** [comment]
I can do the German translation I'm a native speaker. Let me know.

**Comment by JeremyLARDENOIS** [comment]
I can do for french too if you want :)
