### ISSUE TITLE
Consider adding lessons of ES6 features of JavaScript

### ISSUE THREAD

**Issue by giridhar7632** [microsoft/Web-Dev-For-Beginners#176]
In the section of [js-basics](https://github.com/microsoft/Web-Dev-For-Beginners/tree/main/2-js-basics) we can add some lessons about basic ES6 features of JavaScript such as 'let and const', 'scopes', 'template literals', 'arrow functions', 'array de-structuring' etc.
 There's no need of creating a video(if not possible) and mark them as additional features.

**Comment by jlooper** [comment]
Hi, we won’t add more lessons as but the embedded video content does cover those topics
