### ISSUE TITLE
Make tutorials on Bootstrap

### ISSUE THREAD

**Issue by MrGithub2021** [microsoft/Web-Dev-For-Beginners#214]
Hello Microsoft, I am MrGithub2021 and i would very  much like it if you did tutorials on Bootstrap. The reason for this is that
Bootstrap is great for styling webpages.
I would very much like it if you did that.
Sincerely, MrGithub2021.
👍

**Comment by jlooper** [comment]
hi, thanks for the feedback. That would have to be in another type of tutorial and not this curriculum, as we stayed away from this type of library. But thank you for the idea!
