### ISSUE TITLE
2-intro-to-css - some thins are wrong

### ISSUE THREAD

**Issue by kartofelek007** [microsoft/Web-Dev-For-Beginners#216]
https://github.com/microsoft/Web-Dev-For-Beginners/tree/main/3-terrarium/2-intro-to-css has many issues:

_"Cascading Style Sheets incorporate the idea that the styles 'cascade' such that the application of a style is guided by its priority. Styles set by a web site author take priority over those set by a browser. Styles set 'inline' take priority over those set in an external style sheet."_

Yes this is true, but incomplete.
Styles can be from different resources. Some are inline, some are from different css files, js, browser etc. This all resources is mixed into one "source of truth" who is apply into view. 
In this source of truth there is something like "specifity".
Lots of styles apply in order - from top to bottom. This meaning that bottom style for specific element can overwrite top style who change this element. But this is not always true. Some selectors have more power that other. Class is less important like id, id is less important like style inline etc. 
http://www.standardista.com/css3/css-specificity/

_"Styles are inherited from an ancestor style to a descendent, such that nested elements inherit the styles of their parents."_
https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/3-terrarium/2-intro-to-css/README.md#inheritance
Maybe you add sobething like that: 
But you do not have to worry about it. Most styles is not inherited. Only properties for text, border-collapse, cursor and list-style (and some minor properties). For example if you add border to body element, it does not mean that all elements on page will have border. You can force this by "inherit" value, but this is not default.
https://www.w3.org/TR/CSS21/propidx.html

_"Absolute positioned elements are positioned relative to their nearest positioned ancestors, and if there are none, it is positioned according to the document body."_

Not document body, but first screen (first containing block)
https://developer.mozilla.org/en-US/docs/Web/CSS/position
https://codepen.io/kartofelek007/pen/QWGBWgM

https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/3-terrarium/2-intro-to-css/README.md#css-layouts
_"Mixing position properties (there are static, relative, fixed, absolute, and sticky positions) can be a little tricky, but when done properly it gives you good control over the elements on your pages. "_

But in this example you do this somehow wrong :(

_"Note the use of percentages here, even for the border-radius. If you scale your browser down, you can see how the jar corners scale as well."_

They dont scale well. This is because you mixed % with rem. Run your example in window, change it size and you will see what is wrong. Border-radius in rem will not scale (because they based on :root font-size), but % will. And you will see that this look weird.

Another thing is that jar example show place all elements with % and position:absolute. This is incorrect. I know that this is for super beginer persons. But after read this article what I shoul think?

If you want create "total scale view" (like jpg/png graphic) you can try do all elements in rem/em and then set font-size to 1vw (or other css lock formula). Or use #terrarium like parent element, where you place all .jar parts? Ideally wold be set border-radius in rem (or em/px), and position them absolute to relative parent #terrarium.
Maybe I think to much?

**Comment by jlooper** [comment]
hi, of all this it seems like I might change up the mixing of percentage with rem, can you suggest a fix by sending a PR (it will have to include all source code and all translations)

thanks for the feedback

**Comment by tanav-poswal** [comment]
```
print("hi)
```

**Comment by jlooper** [comment]
I've done some edits to resolve the issue above
