### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by vijayraghul777** [microsoft/Web-Dev-For-Beginners#220]

**Comment by 036-jpg** [comment]
Hello

**Comment by emejinglilcompany** [comment]
Hi hi

**Comment by MrGithub2021** [comment]
Hello!!

**Comment by MrGithub2021** [comment]
I am MrGithub2021 and I am a dev. Check out my profile [My Profile on Github.](https://github.com/MrGithub2021)

**Comment by Zavado311** [comment]
Hello

**Comment by MrGithub2021** [comment]
LOL. This issue is ALL about saying hi.

**Comment by MrGithub2021** [comment]
Zavado311, I just followed you!

**Comment by TheBonelessMan** [comment]
Hello guys. A newbie here

**Comment by tony955084** [comment]
https://twitter.com/wuyuting771006/status/1367879011775311872?s=21

**Comment by jlooper** [comment]
Please don't spam this repo, as it costs me time to clean it up

**Comment by MrGithub2021** [comment]
Thanks, jlooper!

**Comment by Zavado311** [comment]
Can someone please describe what we do here? I mean what we can do in this channel? xD

**Comment by MrGithub2021** [comment]
Here is what GitHub is all about :[The video about GitHub ](https://www.youtube.com/watch?v=w3jLJU7DT5E)
💯

**Comment by AlterCognite** [comment]
yo people!! also a newbie.
