### ISSUE TITLE
Making Decisions in JS - Sketchnote - Incorrect label for < and >

### ISSUE THREAD

**Issue by Refactored236** [microsoft/Web-Dev-For-Beginners#229]
Hi, the symbols/labels in the sketchnote for https://github.com/microsoft/Web-Dev-For-Beginners/tree/main/2-js-basics/3-making-decisions are incorrectly assigned. 

Steps to reproduce the behaviour:
1. Go to Web Dev for Beginners Lesson 6
2. View Sketchnote image
3. See error

Label for < should be Less than, and label for > should be greater than

![image](https://user-images.githubusercontent.com/16748183/111221309-3bedd200-85d2-11eb-9b5e-7ce28311ff97.png)

**Desktop (please complete the following information):**
All
**Smartphone (please complete the following information):**
All
**Additional context**
N\A

**Comment by jlooper** [comment]
😱 woops Tomomi! Is it possible to fix? @girliemac

**Comment by girliemac** [comment]
Ahhh, a good catch! I'll take care of this soon. First, I need to find my Apple Pencil. (blaming on 🐱 )
