### ISSUE TITLE
Web-Dev-For-Beginners

### ISSUE THREAD

**Issue by 52LONG** [microsoft/Web-Dev-For-Beginners#23]
For a beginner, I hope to learn more

**Comment by jlooper** [comment]
How can we help?

**Comment by 52LONG** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/Web-Dev-For-Beginners"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月16日(星期一) 晚上8:39
收件人:&nbsp;"microsoft/Web-Dev-For-Beginners"<Web-Dev-For-Beginners@noreply.github.com&gt;;
抄送:&nbsp;"郑孝龙"<814405253@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/Web-Dev-For-Beginners] Web-Dev-For-Beginners (#23)





 
How can we help?
 
—Thank you, can you recommend me some study materials or tell me how to study?
