### ISSUE TITLE
Access to all diagrams

### ISSUE THREAD

**Issue by Ben-Bromley** [microsoft/Web-Dev-For-Beginners#249]
When I look at the readme for the lessons I think the images are brilliant! They really help me out and I'd love to be able to save them as a collection separate from the .mds and lessons

could there be a single folder containing all of these diagrams?

I think it would really help out myself and others

**Comment by jlooper** [comment]
I like this idea! Let me make the path edits unless you want to PR. @girliemac nice feedback ❤️🙏

**Comment by jlooper** [comment]
@Ben-Bromley I've made the change, and all the sketchnotes are now in their own /sketchnotes folder in the root. Let me know if you find any mistakes!
