### ISSUE TITLE
Git switch vs git checkout

### ISSUE THREAD

**Issue by juanpflores** [microsoft/Web-Dev-For-Beginners#251]
# 🆕  Moving from `git checkout` to `git switch`
**Is your feature request related to a problem? Please describe.**
On Git 2.23 `git switch` was introduce as a specific command to change from one branch to another. The idea behind this change is that git checkout makes more than only changing branches _(like restoring the working tree files)_. 

>The new ‘experimental’ git switch branch command is meant to provide a better interface by having a clear separation, which helps to alleviate the developers’ confusion when using git checkout.
One such example is git checkout <filename> which reverses the modifications of an unstaged file and git checkout <branchname> which switches branch. The dilemma is more when the filename and branch name are the same.

>The new commands, git restore (takes care of operations that change file), and the git switch (takes care of operations that change branches) share out the responsibilities of git checkout in a more intuitive way.

**Describe the solution you'd like**
Since Git is looking forward to moving from `git checkout` to `git switch` in the near future, I would consider changing Module 2.

**Additional context**
- [BlueCast Blog](https://bluecast.tech/blog/git-switch-branch/)
- [Git Docs](https://git-scm.com/docs/git-switch)

**Comment by jlooper** [comment]
Thanks, we will keep an eye out for the change

**Comment by costaDZ** [comment]
Thanks for this info .

**Comment by djibal** [comment]
git switch "branch-name"
git switch

**Comment by Fronizzle** [comment]
> # 🆕 Moving from `git checkout` to `git switch`
> **Is your feature request related to a problem? Please describe.**
> On Git 2.23 `git switch` was introduce as a specific command to change from one branch to another. The idea behind this change is that git checkout makes more than only changing branches _(like restoring the working tree files)_.
> 
> > The new ‘experimental’ git switch branch command is meant to provide a better interface by having a clear separation, which helps to alleviate the developers’ confusion when using git checkout.
> > One such example is git checkout  which reverses the modifications of an unstaged file and git checkout  which switches branch. The dilemma is more when the filename and branch name are the same.
> 
> > The new commands, git restore (takes care of operations that change file), and the git switch (takes care of operations that change branches) share out the responsibilities of git checkout in a more intuitive way.
> 
> **Describe the solution you'd like**
> Since Git is looking forward to moving from `git checkout` to `git switch` in the near future, I would consider changing Module 2.
> 
> **Additional context**
> 
> * [BlueCast Blog](https://bluecast.tech/blog/git-switch-branch/)
> * [Git Docs](https://git-scm.com/docs/git-switch)

https://github.com/microsoft/Web-Dev-For-Beginners/issues/251#issue-847914919

**Comment by Fronizzle** [comment]
Git switch

**Comment by eazydripz** [comment]
🦍

**Comment by djibal** [comment]
git switch  -m "`switch-branch` in #checkout-instruction .git"

**Comment by iamsuryakant** [comment]
Thanks for this info.

**Comment by jlooper** [comment]
Please feel free to make a PR, updating all translations, thanks!

**Comment by friendyou1** [comment]
Chip or so D

**Comment by Rodrigostrong** [comment]
Muito bom

**Comment by Guntherbs268** [comment]
Password for AppStore

**Comment by Guntherbs268** [comment]
I just can Not Open the AppStore

**Comment by Guntherbs268** [comment]
I hope ir Workshop

**Comment by genzyy** [comment]
> Please feel free to make a PR, updating all translations, thanks!

Can I take this up?
