### ISSUE TITLE
Some translations are incomplete, so let's audit them and assign folks to fix.

### ISSUE THREAD

**Issue by Dsompa** [microsoft/Web-Dev-For-Beginners#277]
I'd be in for the German translation. Waiting for your reply. 

Some translations are incomplete, so let's audit them and assign folks to fix.

If you'd like to start a draft PR while your translation work is in progress, please do so and follow these instructions: https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/TRANSLATIONS.md

- [ ] Spanish
- [ ] Indonesian
- [x] Hindi
- [ ] German
- [x] Japanese
- [x] Italian
- [x] Korean
- [ ] Portuguese
- [ ] Dutch
- [x] Chinese - Traditional
- [x] Chinese - Simplified
- [ ] Greek
- [x] Malay
- [ ] French
- [ ] Urdu
- [ ] Swahili
- [ ] Russian

__Originally posted by @jlooper in https://github.com/microsoft/Web-Dev-For-Beginners/issues/171__

**Comment by jlooper** [comment]
You can audit the German translations and start a draft PR, thank you
