### ISSUE TITLE
Link Not working 

### ISSUE THREAD

**Issue by Atharva-k** [microsoft/Web-Dev-For-Beginners#28]
### **In**  **Web-Dev-For-Beginners/1-getting-started-lessons/1-intro-to-programming-languages/README.md**

_For the Assignment section link is not working ._

**Comment by Cerchie** [comment]
Hi, 
Can you add a screenshot and write down the steps you have to take to replicate the error?

**Comment by jlooper** [comment]
I've fixed this, it was my mistake when moving to docsify.
