### ISSUE TITLE
Fixed reference link to canvas lesson in main readme and translations

### ISSUE THREAD

**Issue by Alvinchongry** [microsoft/Web-Dev-For-Beginners#287]
Fixed reference link to canvas lesson in main readme and translations

__Originally posted by @ThesllaDev in https://github.com/microsoft/Web-Dev-For-Beginners/pull/285__

__Originally posted by @Alvinchongry in https://github.com/microsoft/Web-Dev-For-Beginners/issues/286__

**Comment by jlooper** [comment]
Complete, I think
