### ISSUE TITLE
Incorrect video link

### ISSUE THREAD

**Issue by pankaj892** [microsoft/Web-Dev-For-Beginners#296]
In the readme file the link of the video is incorrect as the link points out to intro of JavaScript video whereas the lesson is about Arrays and loops.
The link should point out to video of Arrays in JavaScript

https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/2-js-basics/4-arrays-loops/README.md

**Comment by jlooper** [comment]
hi, please feel free to make a PR, updating all translations as well, thanks!
