### ISSUE TITLE
Offline support with PWA (Progressive Web Apps)

### ISSUE THREAD

**Issue by hexatester** [microsoft/Web-Dev-For-Beginners#3]
How about turning this repo into a PWA using [docsify.js](https://docsify.js.org/)?

**Comment by hexatester** [comment]
Or with [jekyll-pwa](https://github.com/lavas-project/jekyll-pwa)

**Comment by jlooper** [comment]
excellent idea! Let me look into it!

**Comment by jlooper** [comment]
added readmes
