### ISSUE TITLE
next word not highlighted when using `childNodes`.

### ISSUE THREAD

**Issue by hikari-dev** [microsoft/Web-Dev-For-Beginners#301]
**Describe the bug**
![screenshot](https://user-images.githubusercontent.com/59637227/123721626-4bf79c00-d8b9-11eb-9b70-7aee35e4f011.gif)

**Desktop (please complete the following information):**
 - Window 10
 - Chrome
 - Version 91.0.4472.114

#298

**Comment by fddang** [comment]
it seems like due to the "space" character issue. 
Maybe you could check following code section:
```js
// 1st
const spanWords = words.map(function (word) { return `<span>${word} </span>`});

//2nd:
quoteElement.innerHTML = spanWords.join('');
```
please note that :
- in the 1st one, there is a "space" character after ${word}
- in the 2nd one, there is no "space" in ***spanWords.join('')***
