### ISSUE TITLE
Stone Paper Scissors Game 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [microsoft/Web-Dev-For-Beginners#308]
**Is your feature request related to a problem? Please describe.**

I will like to add a stone paper scissor game to this repository 

**Describe the solution you'd like**
I feel that this will help them in getting theirs hand with javascript and games makes new learners more excited to learn it 

**Additional context**

I will like to add like to my Github Repository where I have added all the code and also deployment link so You can play it when you are tired of reviewing PR 😄 

Github : - https://github.com/rohan-kulkarni-25/RPS-Game

Deployement :- https://rohan-kulkarni-25.github.io/RPS-Game/

**Comment by jlooper** [comment]
Hi, we are not seeking this kind of contribution to this curriculum but thank you for the suggestion
