### ISSUE TITLE
Is the comparison operators right?

### ISSUE THREAD

**Issue by hahaws** [microsoft/Web-Dev-For-Beginners#32]
**Describe the bug**

in <https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/2-js-basics/3-making-decisions/README.md#comparison-operators-and-booleans> said `5=>6` can run and the result is `False`

but it did not work

![image](https://user-images.githubusercontent.com/33059912/99350328-00b7ec80-28d9-11eb-8c07-34f9fd937e55.png)

i think it should be `>=`

**Comment by anshuman9999** [comment]
Hello, this is my first time contributing to an open source project. Can I take this issue?

**Comment by sam5403** [comment]
I need help on an app I want to create, any ideas on how to start up a betting app?

**Comment by hahaws** [comment]
> Hello, this is my first time contributing to an open source project. Can I take this issue?

Of course, anyone can contribute to open source projects

**Comment by softchris** [comment]
We welcome contributions in general. Happy to receive such a PR

**Comment by anshuman9999** [comment]
Thank you so much. I have created the PR, please review it

**Comment by jlooper** [comment]
good catch, it should be 5>=6, otherwise it thinks the syntax refers to an arrow function. thanks!
