### ISSUE TITLE
[TRANSLATIONS] - French

### ISSUE THREAD

**Issue by ManuSquall** [microsoft/Web-Dev-For-Beginners#326]
- [x] Base README.md
- [x] for-teachers.md
- [x] Quizzes
- [x] 1-getting-started-lessons base README
   - [x] intro-to-programming-languages README
   - [x] intro-to-programming-languages assignment
   - [x] github-basics README
   - [x] accessibility README
   - [x] accessibility assignment
- [x] 2-js-basics base README
   - [x] data-types README
   - [x] data-types assignment
   - [x] functions-methods README
   - [x] functions-methods assignment
   - [x] making-decisions README
   - [x] making-decisions assignment
   - [x] arrays-loops README
   - [x] arrays-loops assignment
- [x] 3-terrarium base README
   - [x] intro-to-html README
   - [x] intro-to-html assignment
   - [x] intro-to-css README
   - [x] intro-to-css assignment
   - [x] intro-to-DOM-and-closures README
   - [x] intro-to-DOM-and-closures assignment
- [x] 4-typing-game base README
   - [x] typing-game README
   - [x] typing-game assignment
- [x] 5-browser-extension base README
   - [x] about-browsers README
   - [x] about-browsers assignment
   - [x] forms-browsers-local-storage README
   - [x] forms-browsers-local-storage assignment
   - [x] background-tasks-and-performance README
   - [x] background-tasks-and-performance assignment
   - [x] solution base README
   - [x] start base README
- [x] 6-space-game base README
   - [x] introduction README
   - [x] introduction assignment
   - [x] drawing-to-canvas README
   - [x] drawing-to-canvas  assignment
   - [x] moving-elements-around README
   - [x] moving-elements-around  assignment
   - [x] collision-detection README
   - [x] collision-detection assignment
   - [x] keeping-score README
   - [x] keeping-score assignment
   - [x] end-condition README
   - [x] end-condition assignment
- [x] 7-bank-project base README
   - [x] template-route README
   - [x] template-route assignment
   - [x] forms README
   - [x] forms  assignment
   - [x] data README
   - [x] data assignment
   - [x] state-management README
   - [x] state-management  assignment
   - [x] solution base README
   - [x] API base README

**Comment by cannujBarfu0negjiz** [comment]
> * [ ]  Base README.md
> * [x]  for-teachers.md
> * [x]  Quizzes
> * [x]  1-getting-started-lessons base README
>   
>   * [x]  intro-to-programming-languages README
>   * [x]  intro-to-programming-languages assignment
>   * [x]  github-basics README
>   * [x]  accessibility README
>   * [x]  accessibility assignment
> * [ ]  2-js-basics base README
>   
>   * [ ]  data-types README
>   * [ ]  data-types assignment
>   * [ ]  functions-methods README
>   * [ ]  functions-methods assignment
>   * [ ]  making-decisions README
>   * [ ]  making-decisions assignment
>   * [ ]  arrays-loops README
>   * [ ]  arrays-loops assignment
> * [ ]  3-terrarium base README
>   
>   * [ ]  intro-to-html README
>   * [ ]  intro-to-html assignment
>   * [ ]  intro-to-css README
>   * [ ]  intro-to-css assignment
>   * [ ]  intro-to-DOM-and-closures README
>   * [ ]  intro-to-DOM-and-closures assignment
>   * [ ]  solution base README
> * [ ]  4-typing-game base README
>   
>   * [ ]  typing-game README
>   * [ ]  typing-game assignment
> * [ ]  5-browser-extension base README
>   
>   * [ ]  about-browsers README
>   * [ ]  about-browsers assignment
>   * [ ]  forms-browsers-local-storage README
>   * [ ]  forms-browsers-local-storage assignment
>   * [ ]  background-tasks-and-performance README
>   * [ ]  background-tasks-and-performance assignment
>   * [ ]  solution base README
>   * [ ]  start base README
> * [ ]  6-space-game base README
>   
>   * [ ]  introduction README
>   * [ ]  introduction assignment
>   * [ ]  drawing-to-canvas README
>   * [ ]  drawing-to-canvas  assignment
>   * [ ]  moving-elements-around README
>   * [ ]  moving-elements-around  assignment
>   * [ ]  collision-detection README
>   * [ ]  collision-detection assignment
>   * [ ]  keeping-score README
>   * [ ]  keeping-score assignment
>   * [ ]  end-condition README
>   * [ ]  end-condition assignment
> * [ ]  7-bank-project base README
>   
>   * [ ]  template-route README
>   * [ ]  template-route assignment
>   * [ ]  forms README
>   * [ ]  forms  assignment
>   * [ ]  data README
>   * [ ]  data assignment
>   * [ ]  state-management README
>   * [ ]  state-management  assignment
>   * [ ]  solution base README

**Comment by cannujBarfu0negjiz** [comment]
> - [ ] Base README.md
> - [x] for-teachers.md
> - [x] Quizzes
> - [x] 1-getting-started-lessons base README
>    - [x] intro-to-programming-languages README
>    - [x] intro-to-programming-languages assignment
>    - [x] github-basics README
>    - [x] accessibility README
>    - [x] accessibility assignment
> - [ ] 2-js-basics base README
>    - [ ] data-types README
>    - [ ] data-types assignment
>    - [ ] functions-methods README
>    - [ ] functions-methods assignment
>    - [ ] making-decisions README
>    - [ ] making-decisions assignment
>    - [ ] arrays-loops README
>    - [ ] arrays-loops assignment
> - [ ] 3-terrarium base README
>    - [ ] intro-to-html README
>    - [ ] intro-to-html assignment
>    - [ ] intro-to-css README
>    - [ ] intro-to-css assignment
>    - [ ] intro-to-DOM-and-closures README
>    - [ ] intro-to-DOM-and-closures assignment
>    - [ ] solution base README
> - [ ] 4-typing-game base README
>    - [ ] typing-game README
>    - [ ] typing-game assignment
> - [ ] 5-browser-extension base README
>    - [ ] about-browsers README
>    - [ ] about-browsers assignment
>    - [ ] forms-browsers-local-storage README
>    - [ ] forms-browsers-local-storage assignment
>    - [ ] background-tasks-and-performance README
>    - [ ] background-tasks-and-performance assignment
>    - [ ] solution base README
>    - [ ] start base README
> - [ ] 6-space-game base README
>    - [ ] introduction README
>    - [ ] introduction assignment
>    - [ ] drawing-to-canvas README
>    - [ ] drawing-to-canvas  assignment
>    - [ ] moving-elements-around README
>    - [ ] moving-elements-around  assignment
>    - [ ] collision-detection README
>    - [ ] collision-detection assignment
>    - [ ] keeping-score README
>    - [ ] keeping-score assignment
>    - [ ] end-condition README
>    - [ ] end-condition assignment
> - [ ] 7-bank-project base README
>    - [ ] template-route README
>    - [ ] template-route assignment
>    - [ ] forms README
>    - [ ] forms  assignment
>    - [ ] data README
>    - [ ] data assignment
>    - [ ] state-management README
>    - [ ] state-management  assignment
- [ ] >    - [ ] solution base README****

**Comment by MidouWebDev** [comment]
Hey, i speak french so i can help with the translation !

**Comment by ManuSquall** [comment]
Hi @MidouWebDev !! It will be great!! Merci d'avance!

**Comment by MidouWebDev** [comment]
@ManuSquall I will do my best !

**Comment by MidouWebDev** [comment]
@ManuSquall i worked on translating the Base README.md to french : README.fr.md, check my PR #335

**Comment by intimniy** [comment]
Здесь

**Comment by intimniy** [comment]
Но@

**Comment by ManuSquall** [comment]
Deleting ```solution base README``` from ```3-terrarium base README``` because no translation folder into solution.

**Comment by aryasoni98** [comment]
could I work on this?

**Comment by ManuSquall** [comment]
> could I work on this?

Sure! :-)

**Comment by aDrIaNo34500** [comment]
Hui
