### ISSUE TITLE
[TRANSLATIONS]

### ISSUE THREAD

**Issue by APuroChingon** [microsoft/Web-Dev-For-Beginners#338]
- [ ] Base README.md
- [ ] for-teachers.md
- [ ] Quizzes
- [ ] 1-getting-started-lessons base README
   - [ ] intro-to-programming-languages README
   - [ ] intro-to-programming-languages assignment
   - [ ] github-basics README
   - [ ] accessibility README
   - [ ] accessibility assignment
- [ ] 2-js-basics base README
   - [ ] data-types README
   - [ ] data-types assignment
   - [ ] functions-methods README
   - [ ] functions-methods assignment
   - [ ] making-decisions README
   - [ ] making-decisions assignment
   - [ ] arrays-loops README
   - [ ] arrays-loops assignment
- [ ] 3-terrarium base README
   - [ ] intro-to-html README
   - [ ] intro-to-html assignment
   - [ ] intro-to-css README
   - [ ] intro-to-css assignment
   - [ ] intro-to-DOM-and-closures README
   - [ ] intro-to-DOM-and-closures assignment
   - [ ] solution base README
- [ ] 4-typing-game base README
   - [ ] typing-game README
   - [ ] typing-game assignment
- [ ] 5-browser-extension base README
   - [ ] about-browsers README
   - [ ] about-browsers assignment
   - [ ] forms-browsers-local-storage README
   - [ ] forms-browsers-local-storage assignment
   - [ ] background-tasks-and-performance README
   - [ ] background-tasks-and-performance assignment
   - [ ] solution base README
   - [ ] start base README
- [ ] 6-space-game base README
   - [ ] introduction README
   - [ ] introduction assignment
   - [ ] drawing-to-canvas README
   - [ ] drawing-to-canvas  assignment
   - [ ] moving-elements-around README
   - [ ] moving-elements-around  assignment
   - [ ] collision-detection README
   - [ ] collision-detection assignment
   - [ ] keeping-score README
   - [ ] keeping-score assignment
   - [ ] end-condition README
   - [ ] end-condition assignment
- [ ] 7-bank-project base README
   - [ ] template-route README
   - [ ] template-route assignment
   - [ ] forms README
   - [ ] forms  assignment
   - [ ] data README
   - [ ] data assignment
   - [ ] state-management README
   - [ ] state-management  assignment
   - [ ] solution base README

**Comment by jlooper** [comment]
What language?
