### ISSUE TITLE
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/signed)](https://cla.opensource.microsoft.com/microsoft/ML-For-Beginners?pullRequest=273) <br/>All CLA requirements met.

### ISSUE THREAD

**Issue by AfirstS** [microsoft/Web-Dev-For-Beginners#348]
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/signed)](https://cla.opensource.microsoft.com/microsoft/ML-For-Beginners?pullRequest=273) <br/>All CLA requirements met.

_Originally posted by @microsoft-cla[bot] in https://github.com/microsoft/ML-For-Beginners/issues/273#issuecomment-892686420_

**Comment by jlooper** [comment]
Please stop the spam
