### ISSUE TITLE
quiz app url is lost

### ISSUE THREAD

**Issue by chenlujjj** [microsoft/Web-Dev-For-Beginners#357]
> A note about quizzes: All quizzes are contained in this app

The quiz app url in the README.md is lost.
![image](https://user-images.githubusercontent.com/17081528/129766006-010b5d17-7ddd-4c84-984e-9b50d482d175.png)

**Comment by jlooper** [comment]
oh, thank you for telling me. Investigating...

**Comment by jlooper** [comment]
hm, investigating and I think that might have been a bit of down time: the quizzes seem to be up, can you recheck?
