### ISSUE TITLE
[TRANSLATIONS] - Greek

### ISSUE THREAD

**Issue by esentis** [microsoft/Web-Dev-For-Beginners#361]
- [x] Base README.md
- [x] for-teachers.md
- [ ] Quizzes
- [x] 1-getting-started-lessons base README
   - [x] intro-to-programming-languages README
   - [x] intro-to-programming-languages assignment
   - [ ] github-basics README
   - [ ] accessibility README
   - [ ] accessibility assignment
- [x] 2-js-basics base README
   - [ ] data-types README
   - [ ] data-types assignment
   - [ ] functions-methods README
   - [ ] functions-methods assignment
   - [ ] making-decisions README
   - [ ] making-decisions assignment
   - [ ] arrays-loops README
   - [ ] arrays-loops assignment
- [x] 3-terrarium base README
   - [ ] intro-to-html README
   - [ ] intro-to-html assignment
   - [ ] intro-to-css README
   - [ ] intro-to-css assignment
   - [ ] intro-to-DOM-and-closures README
   - [ ] intro-to-DOM-and-closures assignment
   - [ ] solution base README
- [x] 4-typing-game base README
   - [ ] typing-game README
   - [ ] typing-game assignment
- [x] 5-browser-extension base README
   - [ ] about-browsers README
   - [ ] about-browsers assignment
   - [ ] forms-browsers-local-storage README
   - [ ] forms-browsers-local-storage assignment
   - [ ] background-tasks-and-performance README
   - [ ] background-tasks-and-performance assignment
   - [ ] solution base README
   - [ ] start base README
- [x] 6-space-game base README
   - [ ] introduction README
   - [ ] introduction assignment
   - [ ] drawing-to-canvas README
   - [ ] drawing-to-canvas  assignment
   - [ ] moving-elements-around README
   - [ ] moving-elements-around  assignment
   - [ ] collision-detection README
   - [ ] collision-detection assignment
   - [ ] keeping-score README
   - [ ] keeping-score assignment
   - [ ] end-condition README
   - [ ] end-condition assignment
- [x] 7-bank-project base README
   - [ ] template-route README
   - [ ] template-route assignment
   - [ ] forms README
   - [ ] forms  assignment
   - [ ] data README
   - [ ] data assignment
   - [ ] state-management README
   - [ ] state-management  assignment
   - [ ] solution base README

**Comment by jlooper** [comment]
There might be some greek translations already, but please feel free to contribute!

**Comment by esentis** [comment]
@jlooper Hmm thanks for the heads up. However, I haven't found anything translated in Greek 'el' whatsoever, yet. I'll do my best and of course I'll skip, if any, the already translated parts.

**Comment by MelnikovAG** [comment]
It's

**Comment by MelnikovAG** [comment]
Ok

**Comment by jlooper** [comment]
hi, should we do an audit, commit what is done, and close? thank you!
