### ISSUE TITLE
Page reloads not prevented

### ISSUE THREAD

**Issue by nsoseka** [microsoft/Web-Dev-For-Beginners#409]
**Bug description**
The onLInkClick function stops the page reloads by preventing the default behaviour on the a tag. This function is quite well written but is not used properly.

This is how its indicated in the ReadMe.
```javascript
<a href="/dashboard" onclick="onLinkClick()">Login</a>
...
<a href="/login" onclick="onLinkClick()">Logout</a>
```
To fix this issue, we need to pass the event object which is expected by the function already written as such

```javascript
<a href="/dashboard" onclick="onLinkClick(event)">Login</a>
...
<a href="/login" onclick="onLinkClick(event)">Logout</a>
```

**The lesson link below: part 1 of bank app**
[banking app part 1](https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/7-bank-project/1-template-route/README.md)

**Comment by jlooper** [comment]
@sinedied could you take a look please and advise? thanks!

**Comment by sinedied** [comment]
@nsoseka You're completely right, this is a mistake. Would you be open to create a PR to fix that? Thanks!

**Comment by nsoseka** [comment]
@sinedied great. I just submitted a pull request for this fix. Thanks

**Comment by sinedied** [comment]
Merged, thanks for the PR
