### ISSUE TITLE
Improve explanation of part 2 of the bank app project.

### ISSUE THREAD

**Issue by nsoseka** [microsoft/Web-Dev-For-Beginners#415]
**Part 2 bank project unclear and difficult to follow course instructions**
I am currently using this course to teach some students some introduction to web development. Part 2 has been trouble for all of them regarding these issues. I help them figure it out in class but it will be much better to bring these to the general public.

1. The instructions on setting up the bank API are not clearly written. I will love to indicate that they need to clone the project, navigate to the 7-bank-project/api folder and run `npm install` and `npm start` there. 
[Bank API setup instruction link](https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/7-bank-project/api/README.md)
2. I will also like to indicate to them that they need two terminals running for both servers. One for the bank API and then the other for the actual bank code they were already writing up until part 2. `npx lite-server` for the bank app, and `npm install` for the bank API.
[Part 2 bank project app](https://github.com/microsoft/Web-Dev-For-Beginners/tree/main/7-bank-project/2-forms)

These two additions will make this particular section of the course easier to follow along. If its okay, I can create a pull request for these changes.

**Comment by jlooper** [comment]
hi @nsoseka - thank you so much for your feedback. Indeed, these lessons are both important to understand and pretty complicated, so I'd love for you to PR a clarification! 

Also, I'd love to know where you are teaching. Can you reach out? I'm jelooper@microsoft.com - thank you again!

**Comment by nsoseka** [comment]
@jlooper Thanks for the prompt reply. I just submitted a PR for this issue.
[PR link](https://github.com/microsoft/Web-Dev-For-Beginners/pull/416)

Will reach out to you. Thanks lots
