### ISSUE TITLE
[TRANSLATIONS]

### ISSUE THREAD

**Issue by Bilalzaiter** [microsoft/Web-Dev-For-Beginners#428]
- [ ] Base LISMOI.md
- [ ] Pour-professeurs.md
- [ ] Examens
- [ ] 1-Commensons-les lessons de base LISMOI
   - [ ] introduction-aux-languages de programmation- LISMOI
   - [ ] introduction-aux-languages de programmation mission
   - [ ] Les bases de github- LISMOI
   - [ ] accessibilité LISMOI
   - [ ] accessibilité mission
- [ ] 2-Les bas de js LISMOI
   - [ ] Les types de données LISMOI
   - [ ] Les types de données mission
   - [ ] Les méthodes de functions LISMOI
   - [ ] Les méthodes de functions mission
   - [ ] Prendre décisions LISMOI
   - [ ] Prendre décisions mission
   - [ ] arrays-loops LISMOI
   - [ ] arrays-loops mission
- [ ] 3-terrarium base LISMOI
   - [ ] intro-to-html LISMOI
   - [ ] intro-to-html mission
   - [ ] intro-to-css LISMOI
   - [ ] intro-to-css assignment
   - [ ] intro-to-DOM-and-closures README
   - [ ] intro-to-DOM-and-closures assignment
- [ ] 4-typing-game base README
   - [ ] typing-game README
   - [ ] typing-game assignment
- [ ] 5-browser-extension base README
   - [ ] about-browsers README
   - [ ] about-browsers assignment
   - [ ] forms-browsers-local-storage README
   - [ ] forms-browsers-local-storage assignment
   - [ ] background-tasks-and-performance README
   - [ ] background-tasks-and-performance assignment
   - [ ] solution base README
   - [ ] start base README
- [ ] 6-space-game base README
   - [ ] introduction README
   - [ ] introduction assignment
   - [ ] drawing-to-canvas README
   - [ ] drawing-to-canvas  assignment
   - [ ] moving-elements-around README
   - [ ] moving-elements-around  assignment
   - [ ] collision-detection README
   - [ ] collision-detection assignment
   - [ ] keeping-score README
   - [ ] keeping-score assignment
   - [ ] end-condition README
   - [ ] end-condition assignment
- [ ] 7-bank-project base README
   - [ ] template-route README
   - [ ] template-route assignment
   - [ ] forms README
   - [ ] forms  assignment
   - [ ] data README
   - [ ] data assignment
   - [ ] state-management README
   - [ ] state-management  assignment
   - [ ] solution base README

**Comment by Bilalzaiter** [comment]
please let me know if that was right , to proceed.

**Comment by jlooper** [comment]
We have a French issue in progress, so please collaborate there, thanks
