### ISSUE TITLE
Help, I'm new!

### ISSUE THREAD

**Issue by aryaman-a** [microsoft/Web-Dev-For-Beginners#43]
Hi, I'm new to GitHub and I want to start helping out in some project. Could someone be kind enough to just let me know how the code is compiled into one URL and how are they connected here in Github. I understand how the pull requests, branches, issues section, and a little bit of markdown work ( because I took the intro course from the lab ), but I don't get how all this code thrown in the code tab compiles/connects as one and contributes to building the software. Final question: is github only for building websites? Or how and where is the software built here used and applied elsewhere.
**If this is not a project/server that encourages new guys then I deeply apologise and appreciate your time.**
Thanks

**Comment by jlooper** [comment]
Welcome! 

So the best thing would be to read through our module on GitHub, to get used to the process. GitHub is like a forum where people store their code. You can also use it to host web sites by using GitHub pages. Or you can build a web site, store the code here, and deploy it somewhere else like Azure Static Web Apps or Netlify. Lots of options! Please continue the course and see if it becomes clearer how the pieces fit together :) and welcome!
