### ISSUE TITLE
[TRANSLATIONS] - Russian 

### ISSUE THREAD

**Issue by OKitel** [microsoft/Web-Dev-For-Beginners#466]
- [ ] Base README.md
- [x] for-teachers.md
- [ ] Quizzes
- [x] 1-getting-started-lessons base README
   - [x] intro-to-programming-languages README
   - [x] intro-to-programming-languages assignment
   - [x] github-basics README
   - [ ] accessibility README
   - [ ] accessibility assignment
- [ ] 2-js-basics base README
   - [ ] data-types README
   - [ ] data-types assignment
   - [ ] functions-methods README
   - [ ] functions-methods assignment
   - [ ] making-decisions README
   - [ ] making-decisions assignment
   - [ ] arrays-loops README
   - [ ] arrays-loops assignment
- [ ] 3-terrarium base README
   - [ ] intro-to-html README
   - [ ] intro-to-html assignment
   - [ ] intro-to-css README
   - [ ] intro-to-css assignment
   - [ ] intro-to-DOM-and-closures README
   - [ ] intro-to-DOM-and-closures assignment
- [ ] 4-typing-game base README
   - [ ] typing-game README
   - [ ] typing-game assignment
- [ ] 5-browser-extension base README
   - [ ] about-browsers README
   - [ ] about-browsers assignment
   - [ ] forms-browsers-local-storage README
   - [ ] forms-browsers-local-storage assignment
   - [ ] background-tasks-and-performance README
   - [ ] background-tasks-and-performance assignment
   - [ ] solution base README
   - [ ] start base README
- [ ] 6-space-game base README
   - [ ] introduction README
   - [ ] introduction assignment
   - [ ] drawing-to-canvas README
   - [ ] drawing-to-canvas  assignment
   - [ ] moving-elements-around README
   - [ ] moving-elements-around  assignment
   - [ ] collision-detection README
   - [ ] collision-detection assignment
   - [ ] keeping-score README
   - [ ] keeping-score assignment
   - [ ] end-condition README
   - [ ] end-condition assignment
- [ ] 7-bank-project base README
   - [ ] template-route README
   - [ ] template-route assignment
   - [ ] forms README
   - [ ] forms  assignment
   - [ ] data README
   - [ ] data assignment
   - [ ] state-management README
   - [ ] state-management  assignment
   - [ ] solution base README

**Comment by Priiyaa** [comment]
Hi!
Is this issue still open if so then can you please explain what we have to do... ?

**Comment by OKitel** [comment]
> Hi! Is this issue still open if so then can you please explain what we have to do... ?

Hello! Yes, it's open. We have to translate other files from English to Russian. I already translated some files, they are checked in this list. Fork this repo to your PC, create a new branch from master. Translate any file from this list into Russian and then create a Pull Request. If everything is ok, your PR will be accepted. Don't forget to check translated files in this issue.
There is also a [file](https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/TRANSLATIONS.md) about contributing to translation. Read it before starting. Good luck!

**Comment by 0Milkesa** [comment]
Can I get a translation of English to Oromo, like?
