### ISSUE TITLE
Broken link in "Intro to html"

### ISSUE THREAD

**Issue by guilhermesfc** [microsoft/Web-Dev-For-Beginners#514]
**Describe the bug**
In [Intro to html](https://github.com/microsoft/Web-Dev-For-Beginners/tree/main/3-terrarium/1-intro-to-html), the link for additional information on _viewport_ is broken.

**To Reproduce**
Click on the link.

**Screenshots**
![image](https://user-images.githubusercontent.com/10503773/140303012-873f0667-f7e0-4a6d-95c2-6beddf8e1d87.png)
![image](https://user-images.githubusercontent.com/10503773/140303048-8ea878ce-eeaf-499b-84dc-afa8e998adf9.png)

**Comment by ManuSquall** [comment]
Hello @guilhermesfc, thanks for this feedback! The link sould be fixed now, thanks to close this issue.

**Comment by guilhermesfc** [comment]
Issue is fixed
