### ISSUE TITLE
[TRANSLATIONS]

### ISSUE THREAD

**Issue by haripaudyal101** [microsoft/Web-Dev-For-Beginners#523]
Hello, I would like to help with the translation into Hindi, I see that there are already some translations in Hindi, but I don't know if everything is complete or if there are parts to be completed.

**Comment by jlooper** [comment]
hi @haripaudyal101 - there are several Hindi translators, let's create a discussion group on the Discussion Board so you can coordinate the efforts. Closing this and meet you there!
