### ISSUE TITLE
[2-github-basics/] Instruction Misleading

### ISSUE THREAD

**Issue by kate115** [microsoft/Web-Dev-For-Beginners#533]
**Describe the bug**
In [github-basic](https://github.com/microsoft/Web-Dev-For-Beginners/tree/main/1-getting-started-lessons/2-github-basics)
Miss `git branch -M main` in Step 10 Connect your local Git repo with GitHub,
and in Step 11 After `git push -u origin master` got following error
![image](https://user-images.githubusercontent.com/75540720/142677524-310bc0d9-330c-425f-b598-66a5740cd0fd.png)

Another issue is that 
![image](https://user-images.githubusercontent.com/75540720/142678140-689903b9-06eb-4836-96f4-4ba1e254b9a0.png)

"Replace repository_name with your GitHub URL." is misleading.

**To Reproduce**
1. Go to 'https://github.com/microsoft/Web-Dev-For-Beginners/tree/main/1-getting-started-lessons/2-github-basics'
2. Follow the instructions till Step 11 Send local files to GitHub
3. Cannot get the expected result

**Expected behavior**
![image](https://user-images.githubusercontent.com/75540720/142677745-53b423ed-e1cb-4a04-b5d3-ffa0bcc4b7c1.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/75540720/142677524-310bc0d9-330c-425f-b598-66a5740cd0fd.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
The fix should be running  `git branch -M main`  before `git remote add origin ...
`

**Comment by jlooper** [comment]
hi, we've had this comment before. We are assuming that folks have 'main' as the default branch selected, however sometimes this seems to not be the case. I think I'll add a little note to this effect in the lesson. Keeping this open until I make the change or someone can introduce a PR.

**Comment by rauthanshubham1** [comment]
Hi, I am a beginner and  I would like to correct the instruction

**Comment by DaMoochie8trillion** [comment]
> **Describe the bug**
> 
> In [github-basic](https://github.com/microsoft/Web-Dev-For-Beginners/tree/main/1-getting-started-lessons/2-github-basics)
> 
> Miss `git branch -M main` in Step 10 Connect your local Git repo with GitHub,
> 
> and in Step 11 After `git push -u origin master` got following error
> 
> ![image](https://user-images.githubusercontent.com/75540720/142677524-310bc0d9-330c-425f-b598-66a5740cd0fd.png)
> 
> 
> 
> Another issue is that 
> 
> ![image](https://user-images.githubusercontent.com/75540720/142678140-689903b9-06eb-4836-96f4-4ba1e254b9a0.png)
> 
> 
> 
> "Replace repository_name with your GitHub URL." is misleading.
> 
> 
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. Go to 'https://github.com/microsoft/Web-Dev-For-Beginners/tree/main/1-getting-started-lessons/2-github-basics'
> 
> 2. Follow the instructions till Step 11 Send local files to GitHub
> 
> 3. Cannot get the expected result
> 
> 
> 
> **Expected behavior**
> 
> ![image](https://user-images.githubusercontent.com/75540720/142677745-53b423ed-e1cb-4a04-b5d3-ffa0bcc4b7c1.png)
> 
> 
> 
> **Screenshots**
> 
> ![image](https://user-images.githubusercontent.com/75540720/142677524-310bc0d9-330c-425f-b598-66a5740cd0fd.png)
> 
> 
> 
> **Desktop (please complete the following information):**
> 
>  - OS: [e.g. iOS]
> 
>  - Browser [e.g. chrome, safari]
> 
>  - Version [e.g. 22]
> 
> 
> 
> **Smartphone (please complete the following information):**
> 
>  - Device: [e.g. iPhone6]
> 
>  - OS: [e.g. iOS8.1]
> 
>  - Browser [e.g. stock browser, safari]
> 
>  - Version [e.g. 22]
> 
> 
> 
> **Additional context**
> 
> The fix should be running  `git branch -M main`  before `git remote add origin ...
> 
> `

**Comment by kate115** [comment]
Thank you for fixing the issue I had.
