### ISSUE TITLE
Page Navigation

### ISSUE THREAD

**Issue by JorenRothman** [microsoft/Web-Dev-For-Beginners#539]
**Describe the bug**
When navigating to a single lesson page the page scroll does not reset so you will end up in the middle of the page.

**To Reproduce**
1. Go to https://microsoft.github.io/Web-Dev-For-Beginners/#/?id=lessons
2. Click on the link of a singular lesson
3. Page opens on the current scroll offset

**Expected behavior**
The page should start at the top when you navigate to it

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MAC OSX
 - Browser chrome
 - Version 96.0.4664.55

**Comment by Arnavmishra219** [comment]
Sir i can solve this bug.
Can i solve this bug

**Comment by Arnavmishra219** [comment]
If you want

**Comment by Arnavmishra219** [comment]
I try my best

**Comment by Arnavmishra219** [comment]
I saw your website i found that when we clink on the lesson we will redirect to the new page that's good but we are redirect to the middle pf the page that's the problem.
Am i right..

**Comment by raisul9** [comment]
Hello

**Comment by DaMoochie8trillion** [comment]
Yes


Sent from Yahoo Mail for iPhone


On Wednesday, November 24, 2021, 2:28 AM, Arnavmishra219 ***@***.***> wrote:




Sir i can solve this bug.
Can i solve this bug

**Comment by Arnavmishra219** [comment]
i think there was an error in your html file

**Comment by Arnavmishra219** [comment]
So can you give me any reward for solving this bug....

**Comment by jlooper** [comment]
hi, maintainer here. Please don't add a lot of comments here, but rather organize your thoughts on the bug and explain how you'd like to fix it, then post a PR referencing the bug, if it exists. I recommend checking the Docsify documentation to see if it's explained there. There are no bug bounties on this repo, but I will close issues if they become a focus of spam.

**Comment by jlooper** [comment]
this was quickly fixed via a quick search of the Docsify documentation: auto2top: true
