### ISSUE TITLE
[TRANSLATIONS] - 	Telugu

### ISSUE THREAD

**Issue by bharadwajduggaraju** [microsoft/Web-Dev-For-Beginners#554]
- [x] Base README.md
- [x] for-teachers.md
- [ ] Quizzes
- [ ] 1-getting-started-lessons base README
   - [ ] intro-to-programming-languages README
   - [ ] intro-to-programming-languages assignment
   - [ ] github-basics README
   - [ ] accessibility README
   - [ ] accessibility assignment
- [ ] 2-js-basics base README
   - [ ] data-types README
   - [ ] data-types assignment
   - [ ] functions-methods README
   - [ ] functions-methods assignment
   - [ ] making-decisions README
   - [ ] making-decisions assignment
   - [ ] arrays-loops README
   - [ ] arrays-loops assignment
- [ ] 3-terrarium base README
   - [ ] intro-to-html README
   - [ ] intro-to-html assignment
   - [ ] intro-to-css README
   - [ ] intro-to-css assignment
   - [ ] intro-to-DOM-and-closures README
   - [ ] intro-to-DOM-and-closures assignment
- [ ] 4-typing-game base README
   - [ ] typing-game README
   - [ ] typing-game assignment
- [ ] 5-browser-extension base README
   - [ ] about-browsers README
   - [ ] about-browsers assignment
   - [ ] forms-browsers-local-storage README
   - [ ] forms-browsers-local-storage assignment
   - [ ] background-tasks-and-performance README
   - [ ] background-tasks-and-performance assignment
   - [ ] solution base README
   - [ ] start base README
- [ ] 6-space-game base README
   - [ ] introduction README
   - [ ] introduction assignment
   - [ ] drawing-to-canvas README
   - [ ] drawing-to-canvas  assignment
   - [ ] moving-elements-around README
   - [ ] moving-elements-around  assignment
   - [ ] collision-detection README
   - [ ] collision-detection assignment
   - [ ] keeping-score README
   - [ ] keeping-score assignment
   - [ ] end-condition README
   - [ ] end-condition assignment
- [ ] 7-bank-project base README
   - [ ] template-route README
   - [ ] template-route assignment
   - [ ] forms README
   - [ ] forms  assignment
   - [ ] data README
   - [ ] data assignment
   - [ ] state-management README
   - [ ] state-management  assignment
   - [ ] solution base README
   - [ ] API base README

**Comment by bharadwajduggaraju** [comment]
This is my first open source contribution to anything Microsoft Related! Should I create PR's for each file I translate or chunks of files?

**Comment by jlooper** [comment]
hi, translating blocks of files is a good idea. Is there someone who can review the translations?

**Comment by bharadwajduggaraju** [comment]
I'm not sure, but my parents are both native speaks so with their help I could get as accurate translations as I can. If there are some other telugu speakers, they can review my code too.

**Comment by bharadwajduggaraju** [comment]
and for each chunk of files I translate, I create a new PR? then how would the pr's be linked to this issue and complete the tasks that are showing up

**Comment by jlooper** [comment]
Perhaps break up this Issue into groups and PR against that.

**Comment by bharadwajduggaraju** [comment]
ah, that could work. by the end of today i willl try to create a pr for the base and for-teachers md files with the help of my parents to translate into native telugu, and then i will create a pr that can be looked over to get started

**Comment by jlooper** [comment]
thank you! love this family activity :) say hi to Mom and Dad!

**Comment by bharadwajduggaraju** [comment]
okay, so I translated it to the best of my ability and had my parents take a quick look for the first two files. i submitted a pr. for the rest of the files, others could pitch in but when I get the time over break I can try to do other files. ill also be on the lookout for contributions to other Microsoft open source projects because i enjoy doing so!
