### ISSUE TITLE
Edge using the js api window.open does not work

### ISSUE THREAD

**Issue by torbjornljung** [microsoft/Web-Dev-For-Beginners#563]
Hi ! 
I'm using the JS API window.open(url, windowName, [windowFeatures]); 
I've used it for years in Internet Explorer. Now Microsoft Edge does not support it,, I can run it in Edge using IE-Explorer mode for 30 days, but I would like a permanent solution.
My request looks as this: 
newpath=z:\\books\documentary\(doc)1972 summary(1985) 
window.open(newpath, 'explorer');
(drive z is within my local intranet.) 
But when I try do access it from Edge nothing happens at all. Do you know why ? Or could you recommend a workaround ?
Cheers, Torbjorn, Stockholm, Sweden

**Comment by jlooper** [comment]
hi, if you'd like to have a discussion with other folks, you can open a thread on the Discussion boards on this repo, but let's take a look at window.open in Edge. I see some documentation here: https://developer.mozilla.org/en-US/docs/Web/API/Window/open - but it looks like, for accessibility purposes, using this API is not recommended. There are other recommendations and best practices listed in this document, which might help
