### ISSUE TITLE
Microsoft Learn X repository Inconsistency

### ISSUE THREAD

**Issue by pegak** [microsoft/Web-Dev-For-Beginners#565]
**Describe the bug**
Inconsistency between Microsoft Learn and this repository. 

**To Reproduce**
1. Go to this repository Readme.
2. Click on Microsoft Learn link
3. Observe different texts, other from this repository

**Expected behavior**
Warning that Microsoft Learn and this repository might slightly differ and tell users which data is more present.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 97

**Smartphone (please complete the following information):**
 - Device: POCO F2 Pro
 - OS: Android 11
 - Browser: Edge
 - Version: 97

**Additional context**

**Comment by jlooper** [comment]
Yes, MS Learn is distinct from this repo and serves a different purpose.
