### ISSUE TITLE
Not a completely correct answer in Quiz (id: 4, question: 2)

### ISSUE THREAD

**Issue by Steindvart** [microsoft/Web-Dev-For-Beginners#593]
## Problem
In `Lesson 2 - Introduction to GitHub: Post-Lecture Quiz`, in question two "_How would you get all the commits from a remote branch?_", we have not a completely correct answer:
![image](https://user-images.githubusercontent.com/53004350/152916833-2b3f5b00-ca6b-4941-8fc0-17c2058eed6f.png)

Because we get all commits (objects and links) from the remote repository with the command `git fetch` ([doc](https://git-scm.com/docs/git-fetch)).
But in `git pull` ([doc](https://git-scm.com/docs/git-pull)) case we "**Fetch from _and integrate_**". Roughly speaking, by default, `git pull` is a shotcode for a sequence of two commands: `git fetch` (getting changes from the remote) and `git merge` (merging into a local copy).

## Solution
I see several:
1. Mark `git fetch` as `true`.
2. Combine this answer options into one - `git fetch or git pull`.

Also, I think it was a good idea to tell about `git fetch` in [lesson](https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/1-getting-started-lessons/2-github-basics/README.md). That with this command, we only get the changes, but do not merge them into local branches, unlike `git pull`.

**Comment by jlooper** [comment]
How about rephrasing the question: "How would you get and integrate..."?

**Comment by Steindvart** [comment]
@jlooper, this is a good option, but I'm afraid that this topic is not clearly touched upon in the lesson, and the student may have problems with understanding the term "integrate".

**Comment by Steindvart** [comment]
@jlooper, on the other hand, as I understand it, the test is more aimed at arousing interest, and therefore `git fetch` can be left for self-study. So, just clarify question. Yes, I think it will be wonderful :)
