### ISSUE TITLE
Links open blank page on github mobile

### ISSUE THREAD

**Issue by hexatester** [microsoft/Web-Dev-For-Beginners#6]
Issue :
Some links only showing blank page on github mobile app.

Source of issue :
There is no filename in the link.

Fix :
Replace all links like `/1-getting-started-lessons/1-intro-to-programming-languages/` into `/1-getting-started-lessons/1-intro-to-programming-languages/README.md`.
_Because of the first link only works on GitHub web, maybe._

Notes :
Resolving this will also help #3 (preventing docsify.js - page not found)

**Comment by jlooper** [comment]
Guess what I'm doing RIGHT NOW :D - check the offline branch :)

**Comment by hexatester** [comment]
Great!
About the solution folders, we might need to add _short_ README.md to explain them.
What do you think?

**Comment by jlooper** [comment]
Yes, good one, do you want to lend me a hand? I think we should document on the main README as well how to run these offline. Any ideas about the video assets?

**Comment by hexatester** [comment]
We need to host the static files for proper pwa setup (with https), the easiest method probably with github pages.

Videos assets can be cached locally with the service worker, i think.

[Docsify about PWA & service worker](https://docsify.js.org/#/pwa?id=create-serviceworker)

If it's possible to enable github pages for this repo, maybe I can make angular PWA.

**Comment by hexatester** [comment]
> Yes, good one, do you want to lend me a hand? I think we should document on the main README as well how to run these offline. Any ideas about the video assets? 

As you can see, I'm not great at words and sentence (yet). I'll skip docs task for now. 😬

But I'm good at suggesting things. :D

**Comment by jlooper** [comment]
Thank you for the suggestions. I can't implement GH pages or turn this into a web site due to compliance issues, but enabling other folks to launch this as a docs site for themselves is a great idea. Moving branches around now and documenting. Thanks again!
