### ISSUE TITLE
How to complete the Course

### ISSUE THREAD

**Issue by B-3-n-j-a-m-i-n** [microsoft/Web-Dev-For-Beginners#65]
## Amazing Looking Course!
Hi guys! course looks amazing and I'm super enthusiastic about web development, but I don't fully understand how this course works, I'm still a newbie! can anyone help me out with this?

**Comment by jlooper** [comment]
hi, thanks for your feedback. There are a few ways to do it; probably I can specify them more on the README. This is either self-driven content for individuals (fork the repo, go through the exercises) or you could work with an instructor who can coach you. 

Question for you - if we created office hours to teach each lesson, would you be interested in joining?

**Comment by B-3-n-j-a-m-i-n** [comment]
Hi, thanks for responding so soon!
Could you briefly explain how I fork the repo?
I would definitely be interested!

**Comment by jlooper** [comment]
hi, in the upper right corner of the repo, you'll see a button to 'fork' - press that and all the code will be copied to your local repository.

**Comment by singh-ux** [comment]
Thank you for your kind help.
