### ISSUE TITLE
Switched comparative operators for <,>,<=,>= in README.md

### ISSUE THREAD

**Issue by Zhme-Kakarot** [microsoft/Web-Dev-For-Beginners#69]
This is fairly self-explanitory. I realize that the description explains the comparisons properly, but the symbol reads from left to right and are named as such.

Seeing a table with '<' in the first column and the large header of 'Greater than' in the next doesn't bode well for those who may not be mathematically inclined to begin with.

Food for thought.

**Comment by jlooper** [comment]
It's an interesting thought. @paladique do you think a **bolded note** in this area with some explanation?

**Comment by paladique** [comment]
Hi @Zhme-Kakarot, thanks for pointing this out. I agree, these symbols should be read from left to right.

**Comment by alylynn1426** [comment]
Ok
