### ISSUE TITLE
Translation / Localization Guide 

### ISSUE THREAD

**Issue by hexatester** [microsoft/Web-Dev-For-Beginners#7]
Hey, its me again.
It would be great if there is a guide about adding localization.
Thanks.

**Comment by Fortenberryles41** [comment]
> Hey, its me again.
> It would be great if there is a guide about adding localization.
> Thanks.

**Comment by jlooper** [comment]
hi @FloorD this is a good idea, can you perhaps add a file for guidance?

**Comment by marcduiker** [comment]
I am about to start localizing in Dutch for the **1-getting started lessons** section.

@hexatester / @Fortenberryles41 there are [**translations**](https://github.com/microsoft/Web-Dev-For-Beginners/tree/main/1-getting-started-lessons/1-intro-to-programming-languages/translations) folders and these are suitable for localized content. The files in there are named README._<country code>_.md where country code is a two letter abbreviation (ISO_3166-1_alpha-2 standard).

**Comment by jlooper** [comment]
@marcduiker would you mind popping that into a markdown file and linking it from the main README? thanks!

**Comment by jlooper** [comment]
super, thank you!!
