### ISSUE TITLE
How to get the answers of the quizzes

### ISSUE THREAD

**Issue by NormalBoii** [microsoft/Web-Dev-For-Beginners#82]
I have forked the repo and also edited the pre-lecture-quiz.md file. How do I know if my answers are correct or not?

**Comment by jlooper** [comment]
I'm migrating the quizzes to Microsoft Quizzes, please stay tuned

**Comment by jlooper** [comment]
Can you take a look at this and give me your feedback: https://forms.microsoft.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR2humCsRZhxNuI79cm6n0hRUNTBMUVdDSFcwTlNTM1RBSDFJQzNMMVM1MS4u

**Comment by NormalBoii** [comment]
> Can you take a look at this and give me your feedback: https://forms.microsoft.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR2humCsRZhxNuI79cm6n0hRUNTBMUVdDSFcwTlNTM1RBSDFJQzNMMVM1MS4u

Thank you , It was good
