### ISSUE TITLE
Request for feedback: Quiz migration

### ISSUE THREAD

**Issue by jlooper** [microsoft/Web-Dev-For-Beginners#85]
Please give me your feedback on migrating our quizzes to Microsoft Forms. You can test the first pre-quiz here, let me know what you think!

https://forms.microsoft.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR2humCsRZhxNuI79cm6n0hRUNTBMUVdDSFcwTlNTM1RBSDFJQzNMMVM1MS4u

**Comment by LearnerSamuelX** [comment]
It looks good to me.

**Comment by minwook-shin** [comment]
good! 
If translated quiz are added, can the survey support translation?

**Comment by tigersniffs** [comment]
not bad

**Comment by jlooper** [comment]
re: translations: https://support.microsoft.com/en-us/office/language-settings-for-microsoft-forms-b282f9aa-0fe4-4290-b1e1-827a8a35ac27 - looks like it's relying on browsers for full translation support. @minwook-shin can you try this for your language?

**Comment by minwook-shin** [comment]
https://forms.microsoft.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR2humCsRZhxNuI79cm6n0hRUNTBMUVdDSFcwTlNTM1RBSDFJQzNMMVM1MS4u&lang=ko

if use this "&lang=ko", some will be translated. and others text may use the browser's(chromium edge!) translation support. 

thanks you!

**Comment by sonalisikarwar** [comment]
Good questions in quiz. But in quiz questions will start from simple (easy) -> intermediate (not easy and difficult) -> advanced (difficult question).

**Comment by jlooper** [comment]
I don’t understand your feedback, @sonalisikarwar

**Comment by sonalisikarwar** [comment]
I mean in quiz in  starting  or for testing easy questions should be included to build participant's  confidence. It will attract more participants.

**Comment by jlooper** [comment]
@sonalisikarwar our quizzes are carefully designed for two purposes: first, to get the student primed and ready to learn to begin the lesson using the pre-lecture quiz, and second, to check knowledge in the post-lecture quiz. If you would like to fork this curriculum and build out other quizzes for your own purpose, however, please feel free!

**Comment by anoopsunnithan** [comment]
The quiz questions are good.

**Comment by jlooper** [comment]
closing this for now, and I will start the migration!
