### ISSUE TITLE
Bank Project： localhost and 127.0.0.1 behave differently

### ISSUE THREAD

**Issue by tigersniffs** [microsoft/Web-Dev-For-Beginners#89]
When I run "npx live-server",the URL displays in the Edge is "127.0.0.1:8080/login". 
But  login  action is blocked by browser because of CROS .
What the interesting part is when i change  it to "lcoalhost",it works.

So ，i have found that  server.js which under api folder just match "localhost" with regualr expression  in line 30.
generally they should be same thing，do i need to PR for this？
![loopback](https://user-images.githubusercontent.com/18594967/100545190-a97d2900-3295-11eb-9f2e-6a3d71c61d38.png)
![localhost](https://user-images.githubusercontent.com/18594967/100545200-ae41dd00-3295-11eb-9890-d6f99125084b.png)

**Comment by jlooper** [comment]
cc @sinedied

**Comment by sinedied** [comment]
You're right @tigersniffs , the server API only allows `localhost` for CORS, wheras `127.0.0.1` should be allowed too. 

You're welcome to propose a PR 🙂
