### ISSUE TITLE
PRAISE： you know what? This is amazing! especiall the game!

### ISSUE THREAD

**Issue by TobinXu** [microsoft/Web-Dev-For-Beginners#9]

**Comment by polly400** [comment]
@

**Comment by softchris** [comment]
Thank you for that :) I wrote the game, so if you see any features you would like, let me know :)

**Comment by jlooper** [comment]
Thanks!! Tell us what you particularly liked!

**Comment by TobinXu** [comment]
> Thanks!! Tell us what you particularly liked!

the next few days, will！dear madam.

**Comment by TobinXu** [comment]
> Thank you for that :) I wrote the game, so if you see any features you would like, let me know :)

It' amazing! when i finished, i will. In chinese, we will say your works is "NIUBI", you can find someone who tell you how to pronounce it haha :)

**Comment by jlooper** [comment]
谢谢!!

**Comment by FloorD** [comment]
❤️

**Comment by 52LONG** [comment]
❤️
