### ISSUE TITLE
for all videos, add a note to explain that it's a video and what it covers

### ISSUE THREAD

**Issue by jlooper** [microsoft/Web-Dev-For-Beginners#93]
**Is your feature request related to a problem? Please describe.**
Video embeds are presented without context in several lessons and look like screenshots

**Describe the solution you'd like**
Add descriptive text under each to explain what will be explained if the user clicks on a video

**Comment by aryasoni98** [comment]
@jlooper  I would like to work on this issue . Please assign me .

**Comment by jlooper** [comment]
@aryasoni98 that would be fabulous! Thank you

**Comment by dima279** [comment]
✌️

**Comment by donnmega** [comment]
would like to join

**Comment by noorsaba9080** [comment]
Yes

**Comment by jlooper** [comment]
Anyone willing to do this work please hop in

**Comment by jlooper** [comment]
completed for english
