### ISSUE TITLE
Expanding on JS Closure topic

### ISSUE THREAD

**Issue by paladique** [microsoft/Web-Dev-For-Beginners#96]
Quoted from #84 :

> The reason I think the highlighted part needs some change is that, it well explained function scope. But if it is titled with the name Closure, there might be some stuff missing (eg. things like why the state of the outer function can just be initialized once, etc.). I mean Closure is a big topic, and even some experienced developers will have tough time explaining what it is during interviews. So viewers of this curriculum might find it a bit challenging to understand if the target audience is at beginner level.

**Comment by LearnerSamuelX** [comment]
Thank you, glad that I could contribute to enhancing ppl's learning process.

**Comment by jlooper** [comment]
I propose the following callout text at the top:

"JavaScript Closures are a vast and complex topic. This lesson touches on the most basic idea that in this terrarium, you will find a closure: an inner function and an outer function constructed in a way to allow the inner function access to the outer function's scope. For much more information on how this works, please visit [the extensive documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures)."

**Comment by jlooper** [comment]
done!
